package com.sxtanna.aspiriamc.exts

import org.bukkit.DyeColor
import org.bukkit.Material
import org.bukkit.Material.*
import java.text.NumberFormat
import java.util.EnumSet
import java.util.UUID

const val PREF = "&c&lAspiria &a&lCompanies &l»&f&l»&r"
const val BACK = "&c← Click to go back"

internal val SXTANNA_UUID = UUID.fromString("41d1fed5-aa44-432c-ab1b-2810001f3270")

internal val CURRENCIES_FORMAT = NumberFormat.getCurrencyInstance()

internal val COLOR_MATERIAL_ASSOCIATIONS = mapOf<DyeColor, Set<Material>>(
    DyeColor.WHITE to EnumSet
            .of(DIORITE,
                POLISHED_DIORITE,

                BIRCH_PLANKS,
                BIRCH_BOAT,
                BIRCH_BUTTON,
                BIRCH_DOOR,
                BIRCH_LOG,
                BIRCH_WOOD,
                BIRCH_SLAB,
                BIRCH_STAIRS,
                BIRCH_FENCE,
                BIRCH_FENCE_GATE,
                BIRCH_TRAPDOOR,
                BIRCH_PRESSURE_PLATE,
                STRIPPED_BIRCH_LOG,
                STRIPPED_BIRCH_WOOD,
                HEAVY_WEIGHTED_PRESSURE_PLATE,
                IRON_BLOCK,
                IRON_DOOR,
                IRON_TRAPDOOR,
                SAND,
                SANDSTONE,
                SANDSTONE_SLAB,
                SANDSTONE_STAIRS,
                CHISELED_SANDSTONE,
                CUT_SANDSTONE,
                SMOOTH_SANDSTONE,
                MUSHROOM_STEM,
                PAINTING,

                END_STONE,
                END_STONE_BRICKS,

                QUARTZ,
                QUARTZ_BLOCK,
                QUARTZ_PILLAR,
                QUARTZ_SLAB,
                QUARTZ_STAIRS,
                CHISELED_QUARTZ_BLOCK,

                COBWEB,
                AZURE_BLUET,
                OXEYE_DAISY,
                END_ROD,
                SNOW,
                SNOWBALL,
                SNOW_BLOCK,
                STRING,
                FEATHER,
                PAPER,
                BONE,
                BONE_MEAL,
                BONE_BLOCK,
                SUGAR,
                GHAST_SPAWN_EGG,
                POLAR_BEAR_SPAWN_EGG,
                SHEEP_SPAWN_EGG,
                WOLF_SPAWN_EGG,
                TURTLE_SPAWN_EGG,
                MUSIC_DISC_STRAD,
                CAKE,


                WHITE_BANNER,
                WHITE_BED,
                WHITE_CARPET,
                WHITE_CONCRETE,
                WHITE_CONCRETE_POWDER,
                WHITE_GLAZED_TERRACOTTA,
                WHITE_SHULKER_BOX,
                WHITE_STAINED_GLASS,
                WHITE_STAINED_GLASS_PANE,
                WHITE_TERRACOTTA,
                WHITE_TULIP,
                WHITE_WALL_BANNER,
                WHITE_WOOL),
    DyeColor.ORANGE to EnumSet
            .of(ACACIA_BOAT,
                ACACIA_BUTTON,
                ACACIA_DOOR,
                ACACIA_FENCE,
                ACACIA_FENCE_GATE,
                ACACIA_PLANKS,
                ACACIA_SLAB,
                ACACIA_STAIRS,
                ACACIA_TRAPDOOR,
                STRIPPED_ACACIA_LOG,
                STRIPPED_ACACIA_WOOD,

                SADDLE,
                LEATHER,
                BLAZE_ROD,
                BLAZE_POWDER,
                TROPICAL_FISH_SPAWN_EGG,

                TROPICAL_FISH,
                CARROT,
                PUMPKIN_PIE,
                COOKED_SALMON,

                PUMPKIN,
                CARVED_PUMPKIN,
                JACK_O_LANTERN,
                MAGMA_BLOCK,

                ORANGE_BANNER,
                ORANGE_BED,
                ORANGE_CARPET,
                ORANGE_CONCRETE,
                ORANGE_CONCRETE_POWDER,
                ORANGE_DYE,
                ORANGE_GLAZED_TERRACOTTA,
                ORANGE_SHULKER_BOX,
                ORANGE_STAINED_GLASS,
                ORANGE_STAINED_GLASS_PANE,
                ORANGE_TERRACOTTA,
                ORANGE_TULIP,
                ORANGE_WALL_BANNER,
                ORANGE_WOOL),
    DyeColor.MAGENTA to EnumSet
            .of(LILAC,
                ALLIUM,

                BUBBLE_CORAL,
                BUBBLE_CORAL_FAN,
                BUBBLE_CORAL_BLOCK,

                MAGENTA_BANNER,
                MAGENTA_BED,
                MAGENTA_CARPET,
                MAGENTA_CONCRETE,
                MAGENTA_CONCRETE_POWDER,
                MAGENTA_DYE,
                MAGENTA_GLAZED_TERRACOTTA,
                MAGENTA_SHULKER_BOX,
                MAGENTA_STAINED_GLASS,
                MAGENTA_STAINED_GLASS_PANE,
                MAGENTA_TERRACOTTA,
                MAGENTA_WALL_BANNER,
                MAGENTA_WOOL),
    DyeColor.LIGHT_BLUE to EnumSet
            .of(ICE,
                PACKED_ICE,

                DIAMOND,
                DIAMOND_ORE,
                DIAMOND_AXE,
                DIAMOND_HOE,
                DIAMOND_SWORD,
                DIAMOND_SHOVEL,
                DIAMOND_PICKAXE,
                DIAMOND_BLOCK,
                DIAMOND_HORSE_ARMOR,

                DIAMOND_HELMET,
                DIAMOND_CHESTPLATE,
                DIAMOND_LEGGINGS,
                DIAMOND_BOOTS,

                BEACON,

                LIGHT_BLUE_BANNER,
                LIGHT_BLUE_BED,
                LIGHT_BLUE_CARPET,
                LIGHT_BLUE_CONCRETE,
                LIGHT_BLUE_CONCRETE_POWDER,
                LIGHT_BLUE_DYE,
                LIGHT_BLUE_GLAZED_TERRACOTTA,
                LIGHT_BLUE_SHULKER_BOX,
                LIGHT_BLUE_STAINED_GLASS,
                LIGHT_BLUE_STAINED_GLASS_PANE,
                LIGHT_BLUE_TERRACOTTA,
                LIGHT_BLUE_WALL_BANNER,
                LIGHT_BLUE_WOOL),
    DyeColor.YELLOW to EnumSet
            .of(GLOWSTONE,
                GLOWSTONE_DUST,
                MELON,
                HAY_BLOCK,
                HORN_CORAL,
                HORN_CORAL_FAN,
                HORN_CORAL_BLOCK,
                DANDELION,
                DANDELION_YELLOW,
                SUNFLOWER,
                LIGHT_WEIGHTED_PRESSURE_PLATE,
                WHEAT,
                BLAZE_SPAWN_EGG,

                GOLDEN_APPLE,
                ENCHANTED_GOLDEN_APPLE,
                PUFFERFISH,

                GOLDEN_AXE,
                GOLDEN_BOOTS,
                GOLDEN_CARROT,
                GOLDEN_CHESTPLATE,
                GOLDEN_HELMET,
                GOLDEN_HOE,
                GOLDEN_HORSE_ARMOR,
                GOLDEN_LEGGINGS,
                GOLDEN_PICKAXE,
                GOLDEN_SHOVEL,
                GOLDEN_SWORD,
                GOLD_BLOCK,
                GOLD_INGOT,
                GOLD_NUGGET,
                GOLD_ORE,
                SPONGE,
                WET_SPONGE,
                YELLOW_BANNER,
                YELLOW_BED,
                YELLOW_CARPET,
                YELLOW_CONCRETE,
                YELLOW_CONCRETE_POWDER,
                YELLOW_GLAZED_TERRACOTTA,
                YELLOW_SHULKER_BOX,
                YELLOW_STAINED_GLASS,
                YELLOW_STAINED_GLASS_PANE,
                YELLOW_TERRACOTTA,
                YELLOW_WALL_BANNER,
                YELLOW_WOOL),
    DyeColor.LIME to EnumSet
            .of(POISONOUS_POTATO,

                LIME_BANNER,
                LIME_BED,
                LIME_CARPET,
                LIME_CONCRETE,
                LIME_CONCRETE_POWDER,
                LIME_DYE,
                LIME_GLAZED_TERRACOTTA,
                LIME_SHULKER_BOX,
                LIME_STAINED_GLASS,
                LIME_STAINED_GLASS_PANE,
                LIME_TERRACOTTA,
                LIME_WALL_BANNER,
                LIME_WOOL),
    DyeColor.PINK to EnumSet
            .of(PEONY,
                GRANITE,
                POLISHED_GRANITE,

                PORKCHOP,
                CHICKEN,
                RABBIT,

                BRAIN_CORAL,
                BRAIN_CORAL_FAN,
                BRAIN_CORAL_BLOCK,

                PINK_BANNER,
                PINK_BED,
                PINK_CARPET,
                PINK_CONCRETE,
                PINK_CONCRETE_POWDER,
                PINK_DYE,
                PINK_GLAZED_TERRACOTTA,
                PINK_SHULKER_BOX,
                PINK_STAINED_GLASS,
                PINK_STAINED_GLASS_PANE,
                PINK_TERRACOTTA,
                PINK_TULIP,
                PINK_WALL_BANNER,
                PINK_WOOL),
    DyeColor.GRAY to EnumSet
            .of(ANVIL,
                CHIPPED_ANVIL,
                DAMAGED_ANVIL,

                STONE_SHOVEL,
                STONE_PICKAXE,
                STONE_AXE,
                STONE_HOE,
                STONE_SWORD,

                BAT_SPAWN_EGG,
                SILVERFISH_SPAWN_EGG,

                GRAY_BANNER,
                GRAY_BED,
                GRAY_CARPET,
                GRAY_CONCRETE,
                GRAY_CONCRETE_POWDER,
                GRAY_DYE,
                GRAY_GLAZED_TERRACOTTA,
                GRAY_SHULKER_BOX,
                GRAY_STAINED_GLASS,
                GRAY_STAINED_GLASS_PANE,
                GRAY_TERRACOTTA,
                GRAY_WALL_BANNER,
                GRAY_WOOL),
    DyeColor.LIGHT_GRAY to EnumSet
            .of(STONE,
                STONE_SLAB,
                STONE_BRICKS,
                CRACKED_STONE_BRICKS,
                CHISELED_STONE_BRICKS,
                STONE_BRICK_SLAB,
                STONE_BRICK_STAIRS,

                MINECART,
                CHEST_MINECART,
                FURNACE_MINECART,
                TNT_MINECART,
                HOPPER_MINECART,

                ELYTRA,
                SKELETON_SKULL,

                IRON_BARS,
                IRON_INGOT,

                IRON_SHOVEL,
                IRON_PICKAXE,
                IRON_AXE,
                IRON_HOE,
                IRON_SWORD,
                IRON_HORSE_ARMOR,

                IRON_HELMET,
                IRON_CHESTPLATE,
                IRON_LEGGINGS,
                IRON_BOOTS,

                CHAINMAIL_HELMET,
                CHAINMAIL_CHESTPLATE,
                CHAINMAIL_LEGGINGS,
                CHAINMAIL_BOOTS,

                ANDESITE,
                POLISHED_ANDESITE,
                COBBLESTONE,
                COBBLESTONE_SLAB,
                COBBLESTONE_STAIRS,
                COBBLESTONE_WALL,
                GRAVEL,
                CLAY,
                CLAY_BALL,

                EVOKER_SPAWN_EGG,
                SKELETON_SPAWN_EGG,


                DEAD_TUBE_CORAL,
                DEAD_TUBE_CORAL_FAN,
                DEAD_TUBE_CORAL_BLOCK,
                DEAD_BRAIN_CORAL,
                DEAD_BRAIN_CORAL_FAN,
                DEAD_BRAIN_CORAL_BLOCK,
                DEAD_BUBBLE_CORAL,
                DEAD_BUBBLE_CORAL_FAN,
                DEAD_BUBBLE_CORAL_BLOCK,
                DEAD_FIRE_CORAL,
                DEAD_FIRE_CORAL_FAN,
                DEAD_FIRE_CORAL_BLOCK,
                DEAD_HORN_CORAL,
                DEAD_HORN_CORAL_FAN,
                DEAD_HORN_CORAL_BLOCK,

                LIGHT_GRAY_BANNER,
                LIGHT_GRAY_BED,
                LIGHT_GRAY_CARPET,
                LIGHT_GRAY_CONCRETE,
                LIGHT_GRAY_CONCRETE_POWDER,
                LIGHT_GRAY_DYE,
                LIGHT_GRAY_GLAZED_TERRACOTTA,
                LIGHT_GRAY_SHULKER_BOX,
                LIGHT_GRAY_STAINED_GLASS,
                LIGHT_GRAY_STAINED_GLASS_PANE,
                LIGHT_GRAY_TERRACOTTA,
                LIGHT_GRAY_WALL_BANNER,
                LIGHT_GRAY_WOOL),
    DyeColor.CYAN to EnumSet
            .of(HEART_OF_THE_SEA,
                MUSIC_DISC_WAIT,
                TRIDENT,
                PRISMARINE,
                PRISMARINE_BRICKS,
                PRISMARINE_BRICK_SLAB,
                PRISMARINE_BRICK_STAIRS,
                PRISMARINE_CRYSTALS,
                PRISMARINE_SHARD,
                PRISMARINE_SLAB,
                PRISMARINE_STAIRS,

                CYAN_BANNER,
                CYAN_BED,
                CYAN_CARPET,
                CYAN_CONCRETE,
                CYAN_CONCRETE_POWDER,
                CYAN_DYE,
                CYAN_GLAZED_TERRACOTTA,
                CYAN_SHULKER_BOX,
                CYAN_STAINED_GLASS,
                CYAN_STAINED_GLASS_PANE,
                CYAN_TERRACOTTA,
                CYAN_WALL_BANNER,
                CYAN_WOOL),
    DyeColor.PURPLE to EnumSet
            .of(SHULKER_BOX,
                SHULKER_SHELL,

                CHORUS_FRUIT,
                CHORUS_PLANT,
                CHORUS_FLOWER,
                POPPED_CHORUS_FRUIT,

                PURPLE_BANNER,
                PURPLE_BED,
                PURPLE_CARPET,
                PURPLE_CONCRETE,
                PURPLE_CONCRETE_POWDER,
                PURPLE_DYE,
                PURPLE_GLAZED_TERRACOTTA,
                PURPLE_SHULKER_BOX,
                PURPLE_STAINED_GLASS,
                PURPLE_STAINED_GLASS_PANE,
                PURPLE_TERRACOTTA,
                PURPLE_WALL_BANNER,
                PURPLE_WOOL),
    DyeColor.BLUE to EnumSet
            .of(LAPIS_ORE,
                LAPIS_BLOCK,
                LAPIS_LAZULI,
                TUBE_CORAL,
                TUBE_CORAL_FAN,
                TUBE_CORAL_BLOCK,
                ZOMBIE_SPAWN_EGG,

                BLUE_BANNER,
                BLUE_BED,
                BLUE_CARPET,
                BLUE_CONCRETE,
                BLUE_CONCRETE_POWDER,
                BLUE_GLAZED_TERRACOTTA,
                BLUE_ICE,
                BLUE_ORCHID,
                BLUE_SHULKER_BOX,
                BLUE_STAINED_GLASS,
                BLUE_STAINED_GLASS_PANE,
                BLUE_TERRACOTTA,
                BLUE_WALL_BANNER,
                BLUE_WOOL),
    DyeColor.BROWN to EnumSet
            .of(DIRT,
                COARSE_DIRT,
                PODZOL,

                OAK_PLANKS,
                SPRUCE_PLANKS,
                JUNGLE_PLANKS,
                DARK_OAK_PLANKS,

                OAK_LOG,
                SPRUCE_LOG,
                JUNGLE_LOG,
                DARK_OAK_LOG,

                OAK_WOOD,
                SPRUCE_WOOD,
                JUNGLE_WOOD,
                DARK_OAK_WOOD,

                OAK_FENCE,
                SPRUCE_FENCE,
                JUNGLE_FENCE,
                DARK_OAK_FENCE,

                OAK_FENCE_GATE,
                SPRUCE_FENCE_GATE,
                JUNGLE_FENCE_GATE,
                DARK_OAK_FENCE_GATE,

                OAK_SLAB,
                SPRUCE_SLAB,
                JUNGLE_SLAB,
                DARK_OAK_SLAB,

                OAK_BOAT,
                SPRUCE_BOAT,
                JUNGLE_BOAT,
                DARK_OAK_BOAT,

                OAK_DOOR,
                SPRUCE_DOOR,
                JUNGLE_DOOR,
                DARK_OAK_DOOR,

                OAK_STAIRS,
                SPRUCE_STAIRS,
                JUNGLE_STAIRS,
                DARK_OAK_STAIRS,

                OAK_BUTTON,
                SPRUCE_BUTTON,
                JUNGLE_BUTTON,
                DARK_OAK_BUTTON,

                OAK_TRAPDOOR,
                SPRUCE_TRAPDOOR,
                JUNGLE_TRAPDOOR,
                DARK_OAK_TRAPDOOR,

                OAK_PRESSURE_PLATE,
                SPRUCE_PRESSURE_PLATE,
                JUNGLE_PRESSURE_PLATE,
                DARK_OAK_PRESSURE_PLATE,

                STRIPPED_OAK_LOG,
                STRIPPED_SPRUCE_LOG,
                STRIPPED_JUNGLE_LOG,
                STRIPPED_DARK_OAK_LOG,

                STRIPPED_OAK_WOOD,
                STRIPPED_SPRUCE_WOOD,
                STRIPPED_JUNGLE_WOOD,
                STRIPPED_DARK_OAK_WOOD,

                BOOK,
                COCOA_BEANS,
                BOOKSHELF,
                SOUL_SAND,
                DEAD_BUSH,
                TORCH,
                CRAFTING_TABLE,
                FARMLAND,
                LADDER,
                NOTE_BLOCK,
                CHEST,
                DAYLIGHT_DETECTOR,
                DONKEY_SPAWN_EGG,
                COW_SPAWN_EGG,
                HORSE_SPAWN_EGG,
                HUSK_SPAWN_EGG,
                LLAMA_SPAWN_EGG,
                MULE_SPAWN_EGG,
                RABBIT_SPAWN_EGG,
                VILLAGER_SPAWN_EGG,
                WRITABLE_BOOK,
                WRITTEN_BOOK,
                RABBIT_HIDE,
                RABBIT_FOOT,

                GRASS_PATH,
                SIGN,
                ITEM_FRAME,
                PLAYER_HEAD,
                ARMOR_STAND,
                FLOWER_POT,

                LEVER,
                RABBIT_STEW,
                MUSHROOM_STEW,
                BREAD,
                COOKED_PORKCHOP,
                COD,
                COOKED_COD,
                COOKED_CHICKEN,
                POTATO,
                BAKED_POTATO,
                COOKED_RABBIT,
                COOKED_BEEF,
                COOKED_MUTTON,
                COOKIE,
                ROTTEN_FLESH,

                WOODEN_SHOVEL,
                WOODEN_PICKAXE,
                WOODEN_AXE,
                WOODEN_HOE,
                WOODEN_SWORD,
                NAME_TAG,
                SHEARS,
                BOW,
                ARROW,

                LEATHER_HELMET,
                LEATHER_CHESTPLATE,
                LEATHER_LEGGINGS,
                LEATHER_BOOTS,
                SHIELD,
                RAIL,
                ACTIVATOR_RAIL,
                POWERED_RAIL,
                DETECTOR_RAIL,

                BROWN_BANNER,
                BROWN_BED,
                BROWN_CARPET,
                BROWN_CONCRETE,
                BROWN_CONCRETE_POWDER,
                BROWN_GLAZED_TERRACOTTA,
                BROWN_MUSHROOM,
                BROWN_MUSHROOM_BLOCK,
                BROWN_SHULKER_BOX,
                BROWN_STAINED_GLASS,
                BROWN_STAINED_GLASS_PANE,
                BROWN_TERRACOTTA,
                BROWN_WALL_BANNER,
                BROWN_WOOL),
    DyeColor.GREEN to EnumSet
            .of(GRASS,
                TALL_GRASS,
                TALL_SEAGRASS,
                ZOMBIE_HEAD,
                CREEPER_HEAD,
                SCUTE,
                WHEAT_SEEDS,
                SUGAR_CANE,
                KELP,
                ENDER_PEARL,
                ENDER_EYE,
                CREEPER_SPAWN_EGG,
                DROWNED_SPAWN_EGG,
                PARROT_SPAWN_EGG,
                SLIME_SPAWN_EGG,
                ZOMBIE_HORSE_SPAWN_EGG,
                EXPERIENCE_BOTTLE,
                MUSIC_DISC_CAT,
                MUSIC_DISC_FAR,
                MUSIC_DISC_WARD,
                TURTLE_HELMET,
                FERN,
                VINE,
                LILY_PAD,
                SLIME_BALL,
                SLIME_BLOCK,
                LARGE_FERN,
                SEAGRASS,
                SEA_PICKLE,
                CACTUS,
                CACTUS_GREEN,
                GRASS_BLOCK,
                EMERALD,
                EMERALD_ORE,
                EMERALD_BLOCK,

                DRIED_KELP,
                DRIED_KELP_BLOCK,

                OAK_SAPLING,
                SPRUCE_SAPLING,
                BIRCH_SAPLING,
                JUNGLE_SAPLING,
                ACACIA_SAPLING,
                DARK_OAK_SAPLING,

                OAK_LEAVES,
                SPRUCE_LEAVES,
                BIRCH_LEAVES,
                JUNGLE_LEAVES,
                ACACIA_LEAVES,
                DARK_OAK_LEAVES,

                GREEN_BANNER,
                GREEN_BED,
                GREEN_CARPET,
                GREEN_CONCRETE,
                GREEN_CONCRETE_POWDER,
                GREEN_GLAZED_TERRACOTTA,
                GREEN_SHULKER_BOX,
                GREEN_STAINED_GLASS,
                GREEN_STAINED_GLASS_PANE,
                GREEN_TERRACOTTA,
                GREEN_WALL_BANNER,
                GREEN_WOOL),
    DyeColor.RED to EnumSet
            .of(NETHERRACK,
                REDSTONE,
                REDSTONE_BLOCK,
                REDSTONE_ORE,
                BRICK,
                BRICKS,
                BRICK_SLAB,
                BRICK_STAIRS,
                NETHER_BRICK,
                NETHER_BRICKS,
                NETHER_BRICK_FENCE,
                NETHER_BRICK_SLAB,
                NETHER_BRICK_STAIRS,
                NETHER_QUARTZ_ORE,
                NETHER_WART,
                NETHER_WART_BLOCK,

                FIRE_CORAL,
                FIRE_CORAL_FAN,
                FIRE_CORAL_BLOCK,

                POPPY,
                ROSE_BUSH,
                ROSE_RED,
                TNT,
                REPEATER,
                COMPARATOR,
                MOOSHROOM_SPAWN_EGG,
                SALMON_SPAWN_EGG,
                MUSIC_DISC_CHIRP,

                APPLE,
                SALMON,
                BEEF,
                MUTTON,
                BEETROOT,
                BEETROOT_SOUP,

                BARRIER,

                SPIDER_EYE,
                FERMENTED_SPIDER_EYE,
                MELON_SLICE,
                GLISTERING_MELON_SLICE,

                RED_BANNER,
                RED_BED,
                RED_CARPET,
                RED_CONCRETE,
                RED_CONCRETE_POWDER,
                RED_GLAZED_TERRACOTTA,
                RED_MUSHROOM,
                RED_MUSHROOM_BLOCK,
                RED_NETHER_BRICKS,
                RED_SAND,
                RED_SANDSTONE,
                RED_SANDSTONE_SLAB,
                RED_SANDSTONE_STAIRS,
                RED_SHULKER_BOX,
                RED_STAINED_GLASS,
                RED_STAINED_GLASS_PANE,
                RED_TERRACOTTA,
                RED_TULIP,
                RED_WALL_BANNER,
                RED_WOOL),
    DyeColor.BLACK to EnumSet
            .of(COAL_BLOCK,
                WITHER_SKELETON_SKULL,
                DRAGON_HEAD,
                COAL,
                CHARCOAL,
                FLINT,
                INK_SAC,
                ENDERMAN_SPAWN_EGG,
                ENDERMITE_SPAWN_EGG,
                WITHER_SKELETON_SPAWN_EGG,
                FIRE_CHARGE,
                MUSIC_DISC_STAL,
                MUSIC_DISC_11,

                BLACK_BANNER,
                BLACK_BED,
                BLACK_CARPET,
                BLACK_CONCRETE,
                BLACK_CONCRETE_POWDER,
                BLACK_GLAZED_TERRACOTTA,
                BLACK_SHULKER_BOX,
                BLACK_STAINED_GLASS,
                BLACK_STAINED_GLASS_PANE,
                BLACK_TERRACOTTA,
                BLACK_WALL_BANNER,
                BLACK_WOOL))